# Generated by Django 4.1.1 on 2022-09-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_patient_ailment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='consulation_fee',
            field=models.PositiveSmallIntegerField(blank=True, default='500', null=True),
        ),
    ]
